const types = {
    LOGIN_FETCH: "LOGIN/fetch",
    LOGIN_SUCCESS: "LOGIN/success",
    LOGIN_ERROR: "LOGIN/error",
    LOGOUT_USER: "LOGOUT/user",

    REGISTER_FETCH: "REGISTER/fetch",
    REGISTER_SUCCESS: "REGISTER/success",
    REGISTER_ERROR: "REGISTER/error",

    PROFILE_FETCH: "PROFILE/fetch",
    PROFILE_DATA: "PROFILE/data",
    PROFILE_ERROR: "PROFILE/error",
    PROFILE_RESET: "PROFILE/reset",

    CLIENTS_FETCH: "CLIENTS/fetch",
    CLIENTS_DATA: "CLIENTS/data",
    CLIENTS_ERROR: "CLIENTS/error",
    CLIENTS_RESET: "CLIENTS/reset",

    CLIENT_DETAIL_FETCH: "CLIENT_DETAIL/fetch",
    CLIENT_DETAIL_DATA: "CLIENT_DETAIL/data",
    CLIENT_DETAIL_ERROR: "CLIENT_DETAIL/error",

    ADD_CLIENT_FETCH: "ADD_CLIENT/fetch",
    ADD_CLIENT_SUCCESS: "ADD_CLIENT/success",
    ADD_CLIENT_ERROR: "ADD_CLIENT/error",

    DELETE_CLIENT_FETCH: "DELETE_CLIENT/fetch",
    DELETE_CLIENT_SUCCESS: "DELETE_CLIENT/success",
    DELETE_CLIENT_ERROR: "DELETE_CLIENT/error",

    UPDATE_CLIENT_FETCH: "UPDATE_CLIENT/fetch",
    UPDATE_CLIENT_SUCCESS: "UPDATE_CLIENT/success",
    UPDATE_CLIENT_ERROR: "UPDATE_CLIENT/error",
};

export default types;
